[package]
name = "rust_usb"
version = "0.1.0"
edition = "2021"

[[bin]]
path = "src/read_device.rs"
name = "read_device"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libusb = "0.3"


[profile.release]
strip = true
